version: "3.8"

services:
  web:
    # depends_on:
    #   -api

    build: ./store
    image: horattiul/frontend-image
    ports:
      - "5173:5173"

    environment:
      REACT_APP_BACKEND_URL: https://backend-fabricad.onrender.com

  api:
    build: ./backend
    image: horattiul/backend-image
    ports:
      - "8000:8000"
