version: "3.8"

services:
  web:
    depends_on:
      - api

    build: ./store
    image: horattiul/frontend-image
    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://api:8000

  api:
    build: ./backend
    image: horattiul/backend-image
    ports:
      - "8000:8000"
